### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by alessandro-molari** [sindresorhus/hook-std#14]
The following are the types to include typescript support in your project:

```typescript
export type UnhookFunctionType = () => void;
export type HookOpts = { silent: boolean; once: boolean };
export type HookCallback = (str: string, enc: string) => string | boolean;

export function stdout(
  opts: HookOpts | HookCallback,
  cb?: HookCallback
): UnhookFunctionType;

export function stderr(
  opts: HookOpts | HookCallback,
  cb?: HookCallback
): UnhookFunctionType;
```

They should be added to `index.d.ts` in order to provide types out-of-the-box.

**Comment by SamVerschueren** [comment]
Sorry, it's better to publish them to DefinitelyTyped https://github.com/sindresorhus/ama/issues/439. We don't care in maintaining typedef ourselves.

**Comment by sindresorhus** [comment]
I now accept TypeScript definitions if anyone looking is interested in submitting it here.

See: https://github.com/sindresorhus/ama/issues/439#issuecomment-414212229

Please follow this guide: https://github.com/sindresorhus/typescript-definition-style-guide
