### ISSUE TITLE
Allow to hook into any writable stream

### ISSUE THREAD

**Issue by pvdlg** [sindresorhus/hook-std#18]
This would add the option `streams` that would accept an Array of [Writable streams](https://nodejs.org/api/stream.html#stream_writable_streams). By default if would be:
- `[process.stdout, process.stderr]`  when calling `hookStd([options], transform)`
- `[process.stdout]`  when calling `hookStd.stdout([options], transform)`
- `[process.stderr]`  when calling `hookStd.stderr([options], transform)`

The library would then do the same usual, but would get the stream to hook into fro m the new option rather than from `process`.

**Comment by sindresorhus** [comment]
Seems like a good option to have. What is your use-case?

It is a little bit weird that `hookStd.stdout({streams: [process.stderr]})` would be allowed. Should we maybe contain the option to the main `hookStd()`? Or do you have a use-case I'm not seeing?

**Comment by pvdlg** [comment]
I guess when using `hookStd.stdout` and `hookStd.stderr` the `streams` option will be ignored.

The use case is to use a transform function to replace sensitive text from the console output. I also want the user to be able to customize the `stdout` and `stderr` used by the library and ultimately pass them to [signale](https://github.com/klauscfhq/signale#streams).

**Comment by sindresorhus** [comment]
> I guess when using hookStd.stdout and hookStd.stderr the streams option will be ignored.

👍

**Comment by sindresorhus** [comment]
Alright. PR welcome :)

**Comment by pvdlg** [comment]
Here is the PR: #19
